#!/usr/bin/env python2

import json
import apt
import sys
import uuid
import os
import subprocess

for packageFile in sys.stdin:
    session_id = uuid.uuid4().urn[9:]

    injectablePackageName = subprocess.check_output(['dpkg-deb',
                                '-f',
                                packageFile.split('\n')[0],
                                'Package']).split('\n')[0]

    print("Injectable Package Name: " + injectablePackageName)
    if os.path.exists('/var/cache/apt/archives/lock'):
        os.rename('/var/cache/apt/archives/lock',
            '/var/cache/apt/archives/lock.' + session_id)

    confdir = '/etc/depinject/conf.d'

    for config in os.listdir(confdir):
        if config.endswith('.json'):
            with open(confdir + '/' + config) as data_file:
                deps = json.load(data_file)
                if injectablePackageName == deps['x-depinject']:
                    for dependency in deps['dependencies']:
                        print("Installing " + dependency['name'])
                        os.system("apt-get -y --force-yes install " + dependency['name'])

    os.rename('/var/cache/apt/archives/lock.' + session_id,
        '/var/cache/apt/archives/lock')
